services:
    webkul_shopify_connector.quick_export_job:
        class: '%pim.batch_job.service.class%'
        arguments:
            - '%webkul_shopify_connector.quick_export_job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.shopify_category.quick_export'
                - '@webkul.step.shopify_product.quick_export'
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_shopify.connector.name%', type: '%pim_enrich.job.quick_export_type%' }