services:
    #v2.2
    webkul_shopify.processor.product:
        class: '%pim_connector.processor.normalization.product.class%'
        arguments:
            - '@webkul_shopify.product.normalizer' # - '@pim_catalog.normalizer.standard.product'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'  # - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_connector.processor.bulk_media_fetcher'
            - '@pim_catalog.values_filler.product'
            - '@pim_connector.doctrine.cache_clearer'