extensions:
    pim-job-instance-shopify-data-mapping-import-show:
        module: pim/form/common/edit-form

    pim-job-instance-shopify-data-mapping-import-show-main-image:
        module: pim/form/common/main-image
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: main-image
        config:
            path: bundles/shopify/images/shopify-akeneo-connector.png

    pim-job-instance-shopify-data-mapping-import-show-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-job-instance-shopify-data-mapping-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pim-job-instance-shopify-data-mapping-import-show-launch:
        module: pim/job/common/edit/launch
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: meta
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.import.title
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    pim-job-instance-shopify-data-mapping-import-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: title
        position: 100

    pim-job-instance-shopify-data-mapping-import-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    pim-job-instance-shopify-data-mapping-import-show-subsection:
        module: pim/form/common/subsection
        parent: pim-job-instance-shopify-data-mapping-import-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    pim-job-instance-shopify-data-mapping-import-show-grid:
        module: pim/job/common/grid
        parent: pim-job-instance-shopify-data-mapping-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import