# extensions:
#     shopify_quick_export_products:
#         module: shopify/common/meta
#         parent: pim-mass-product-edit
#         position: 600
#         config:
#             title: pim_enrich.mass_edit.product.title
#             label: 'Quick export'
#             labelCount: "{1}Add comment to <span class=\"AknFullPage-title--highlight\">1 product</span>|]1, Inf[Add comment to <span class=\"AknFullPage-title--highlight\">{{ itemsCount }} products</span>"
#             description: 'Add a comment for a set of products'
#             code: add_comment
#             jobInstanceCode: add_comment
#             icon: icon-template
