extensions:
# #     # menu item
    pim-menu-shopify:
        module: pim/menu/tab
        parent: pim-menu
        position: 120
        targetZone: mainMenu
        aclResourceId: pim_importexport_export_profile_index
        config:
            title: shopify.connector
            iconModifier: iconWebkulShopify
            to: webkul_shopify_connector_configuration

    webkul-shopify-connector-configuration-form:
        module: shopify/form/configuration

    webkul-shopify-connector-configuration-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: webkul-shopify-connector-configuration-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-shopify

    webkul-shopify-connector-configuration-title:
        module: pim/common/grid-title
        parent: webkul-shopify-connector-configuration-form
        targetZone: title
        config:
            title: shopify.connector.title
            countable: false

    webkul-shopify-connector-configuration-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-shopify-connector-configuration-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    # # Buttons
    webkul-shopify-connector-configuration-save:
        module: shopify/form/configuration/save
        parent: webkul-shopify-connector-configuration-form
        targetZone: buttons
        position: 100

    webkul-shopify-connector-configuration-tab-import-jobs:
        module: shopify/form/configuration/import/jobs
        parent: webkul-shopify-connector-configuration-form
        targetZone: buttons
        position: 110
    
    webkul-shopify-connector-configuration-tab-jobs:
        module: shopify/form/configuration/jobs
        parent: webkul-shopify-connector-configuration-form
        targetZone: buttons
        position: 120

    

    # # Tabs
    webkul-shopify-connector-configuration-tabs:
        module: pim/form/common/form-tabs
        parent: webkul-shopify-connector-configuration-form
        targetZone: content
        position: 100

    webkul-shopify-connector-configuration-tab-documentation:
        module: shopify/form/configuration/tab/documentation
        parent: webkul-shopify-connector-configuration-tabs
        targetZone: container
        position: 110
        config:
            title: shopify.documentation

    webkul-shopify-connector-configuration-tab-credential:
        module: shopify/form/configuration/tab/credential
        parent: webkul-shopify-connector-configuration-tabs
        targetZone: container
        position: 120
        config:
            title: shopify.credentials

    webkul-shopify-connector-configuration-tab-exportsettings:
        module: shopify/form/configuration/tab/export-settings
        parent: webkul-shopify-connector-configuration-tabs
        targetZone: container
        position: 130
        config:
            title: shopify.settings

    webkul-shopify-connector-configuration-tab-importsettings:
        module: shopify/form/configuration/tab/import-settings
        parent: webkul-shopify-connector-configuration-tabs
        targetZone: container
        position: 140
        config:
            title: shopify.import

    webkul-shopify-connector-configuration-tab-other-settings:
        module: shopify/form/configuration/tab/other-settings
        parent: webkul-shopify-connector-configuration-tabs
        targetZone: container
        position: 150
        config:
            title: shopify.other.settings

    webkul-shopify-connector-configuration-state:
        module: pim/form/common/state
        parent: webkul-shopify-connector-configuration-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.title
    
    # Attribute Mapping Model
    webkul-shopify-data-mapping-connector-create-instance-modal:
        module: custom/form/configuration/create/modal
        config:
            labels:
                title: webkul_shopify_data_mapping_connector.create_popin.title
                subTitle: webkul_shopify_data_mapping_connector.item.credential
            picture: illustrations/Groups.svg
            successMessage: pim_enrich.entity.group_type.message.created
            editRoute: webkul_product_export_edit
            postUrl: webkul_product_export_create
            routerKey: id
 
    webkul-shopify-data-mapping-connector-create-instance-modal-host:
        module: custom/form/configuration/create/form
        parent: webkul-shopify-data-mapping-connector-create-instance-modal
        targetZone: fields
        position: 10
        config:
            labels:
                title: webkul_shopify_data_mapping_connector.create_popin.title
                subTitle: webkul_shopify_data_mapping_connector.item.export_mapping
            identifier: host
            label: webkul_shopify_data_mapping_connector.hostName
