parameters:
    webkul_shopify.product.export.step: 'Webkul\ShopifyBundle\Steps\ProductExportStep'
    webkul_shopify.category.export.step: 'Webkul\ShopifyBundle\Steps\CategoryExportStep'
    # webkul_shopify.attribute.export.step: 'Webkul\ShopifyBundle\Steps\AttributeExportStep'
    # webkul_shopify.attribute_option.export.step: 'Webkul\ShopifyBundle\Steps\AttributeOptionExportStep'

services:   
    webkul.step.shopify_product.export:
        class: '%webkul_shopify.product.export.step%'
        arguments:
            - 'product_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@webkul_shopify.processor.product'
            - '@webkul_shopify.writer.product.api'
            - 10

    webkul.step.shopify_category.export:
        class: '%webkul_shopify.category.export.step%'
        arguments:
            - 'category_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@shopify.reader.database.category'        
            - '@pim_connector.processor.normalization.category'
            - '@webkul_shopify.writer.category.api' 
            - 10
            
    webkul.step.shopify_category.quick_export:
        class: '%webkul_shopify.category.export.step%'
        arguments:
            - 'category_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@shopify.reader.database.category.quick_export'
            - '@pim_connector.processor.normalization.category'
            - '@webkul_shopify.writer.category.api' 
            - 10
            
    webkul.step.shopify_product.quick_export:
        class: '%webkul_shopify.product.export.step%'
        arguments:
            - 'product_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.reader.database.product_and_product_model'
            # - '@pim_enrich.connector.processor.quick_export.product'
            - '@webkul_shopify.processor.quick_export.product'
            - '@webkul_shopify.writer.product.api'
            - 10
    
    webkul.step.shopfiy_category_import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'category_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.category'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'
            - 10
            
    webkul.step.shopify_product_import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'product_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.product'
            - '@pim_connector.processor.denormalization.product'
            - '@pim_connector.writer.database.product'
            - 10

    webkul.step.shopify_product_model_import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'product_model_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.product_model'
            - '@webkul_shopify.processor.denormalization.root_product_model'
            - '@pim_connector.writer.database.product_model'
            - 10
    
    webkul.step.shopify_product_models_descendants.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_product_model_descendants'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.product_model'
            - '@pim_connector.processor.denormalization.product_model_loader'
            - '@pim_connector.writer.database.product_model_descendants'
            - 10

    webkul.step.shopify_attribute.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'attribute_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.attribute'                     #'@pim_connector.reader.file.csv_attribute'
            - '@pim_connector.processor.denormalization.attribute'
            - '@pim_connector.writer.database.attribute'
            - 10        

    webkul.step.shopify_attribute_option.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'attribute_option_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.attribute_option'              #'@pim_connector.reader.file.csv_attribute_option'
            - '@pim_connector.processor.denormalization.attribute_option'
            - '@pim_connector.writer.database.attribute_option'
            - 10

    webkul.step.shopify_family_variant.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'family_variant_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@webkul_shopify.reader.import.family_variant'                #'@pim_connector.reader.file.csv_family_variant'
            - '@pim_connector.processor.denormalization.family_variant'
            - '@pim_connector.writer.database.family_variant'
            - 10
        
    