datagrid:
    product-grid:
        mass_actions:
            quick_export_shopify:
                type: export
                label: pim.grid.mass_action.quick_export.shopify
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:
                    _format: html
                    _contentType: text/html
                    _jobCode: shopify_product_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export